coverage:
  precision: 2
  range:
    - 60.0
    - 80.0
  round: down
  status:
    patch:
      default:
        target: 80.0
    project:
      default:
        target: auto
        threshold: 1%
ignore:
  - "**/*_test.go"
