version: "2"
run:
  go: "1.23"
  modules-download-mode: readonly
  issues-exit-code: 2
  tests: false
  allow-parallel-runners: true
  allow-serial-runners: true
output:
  path-prefix: ""
linters:
  default: all
  disable:
    - asasalint
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - depguard
    - durationcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exhaustruct
    - exptostd
    - fatcontext
    - forbidigo
    - forcetypeassert
    - ginkgolinter
    - gochecknoglobals
    - gochecksumtype
    - gocritic
    - gosec
    - gosmopolitan
    - govet
    - iface
    - importas
    - intrange
    - ireturn
    - lll
    - loggercheck
    - makezero
    - mirror
    - musttag
    - nilerr
    - nilnesserr
    - nilnil
    - nlreturn
    - noctx
    - nonamedreturns
    - paralleltest
    - perfsprint
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagliatelle
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usetesting
    - varnamelen
    - wastedassign
    - wrapcheck
    - wsl
    - zerologlint
  settings:
    funlen:
      lines: 90
      ignore-comments: true
    interfacebloat:
      max: 15
    revive:
      max-open-files: 2048
      severity: error
      enable-all-rules: true
      rules:
        - name: add-constant
          arguments:
            - allowFloats: 0.0,0.,1.0,1.,2.0,2.
              allowInts: 0,1,2
              allowStrs: '""'
              maxLitCount: "3"
          severity: warning
          disabled: false
        - name: blank-imports
          severity: warning
          disabled: true
        - name: cognitive-complexity
          arguments:
            - 8
          severity: warning
          disabled: false
        - name: line-length-limit
          arguments:
            - 180
          severity: warning
          disabled: false
        - name: unexported-return
          severity: warning
          disabled: true
    varnamelen:
      max-distance: 6
      min-name-length: 1
      check-receiver: true
      check-return: true
      check-type-param: true
      ignore-names:
        - err
      ignore-type-assert-ok: true
      ignore-map-index-ok: true
      ignore-chan-recv-ok: true
      ignore-decls:
        - c echo.Context
        - t testing.T
        - f *foo.Bar
        - e error
        - i int
        - const C
        - T any
        - m map[string]int
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  settings:
    goimports:
      local-prefixes:
        - github.com/a-x-a
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
